### PR TITLE
package.json: Add "repository" information

### LINKED ISSUE #3: No "repository" field in "package.json"
At https://emberobserver.com/addons/ember-baremetrics-calendar the wrong repository link is used, which can be fixed by filling in the `repository` field of the `package.json` file.

### PR DESCRIPTION
**Pull request by Turbo87**
Resolve #3

### CODE REVIEW

**Comment by Turbo87** [comment]
@davewasmer do you want me to rebase?

**Comment by davewasmer** [comment]
Sure 👍

**Comment by Turbo87** [comment]
@davewasmer done!

**Comment by Turbo87** [comment]
it seems that the build failures are unrelated to the changes in this PR

**Comment by Turbo87** [comment]
@davewasmer friendly reminder... 😉

**Comment by davewasmer** [comment]
Thanks for following up @Turbo87!

**Pull request merged**
